[tool.coverage.run]
branch = true
source = ["ml-deep-learning-utils"]

[tool.coverage.report]
exclude_also = [
    "raise AssertionError",
    "raise NotImplementedError",
    "@(abc\\.)?abstractmethod"
]